### ISSUE TITLE
Report files and lines for the sources of conflicts

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/gradle-apilint#61]
Integrating API lint into Mozilla's Phabricator CI (see [Bug 1512487](https://bugzilla.mozilla.org/show_bug.cgi?id=1512487)) comes with some requirements.  Fundamentally, Phab can only display lint issues as comments anchored to a file and a line, and then only when the file and line are actually part of the commit in question.

Can we teach API lint to report the file and line of changed signatures?  I feel like that information is probably already present but not captured in output by default, but I know there are layers of APIs in between the sources and the outputs, and maybe the source mapping is lost too early to achieve this.

**Comment by agi90** [comment]
We definitely do have this piece of information, any element in the Doclet API has a [`SourcePosition`][1] object that gives you what you want.

We would need to build a source map file that apilint can then use to figure out where each file is, but it shouldn't be too complicated.

[1]: https://docs.oracle.com/javase/7/docs/jdk/api/javadoc/doclet/com/sun/javadoc/Doc.html#position()

**Comment by agi90** [comment]
The source map can probably just be a json file with something like:

```json
{
    "org.mozilla.geckoview.GeckoView": {
        "class": {
            "column": "...",
            "file": "...",
            "line": "..."
        },
        "members": {
            "method public void coverUntilFirstPaint(int)": {
                "column": "...",
                "file": "...",
                "line": "..."
            },
        }
    },
    "org.mozilla.geckoview.GeckoSession": {
    },
}
```
